// <auto-generated />
using System;
using Buscador.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buscador.Data.Migrations
{
    [DbContext(typeof(BuscadorContext))]
    [Migration("20241009105420_Prueba25")]
    partial class Prueba25
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Buscador.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Nombre = "Moda"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Nombre = "Banca"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Nombre = "Telecomunicaciones"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Nombre = "Energía"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Nombre = "Distribución"
                        },
                        new
                        {
                            IdCategoria = 6,
                            Nombre = "Automotriz"
                        },
                        new
                        {
                            IdCategoria = 7,
                            Nombre = "Infraestructura"
                        },
                        new
                        {
                            IdCategoria = 8,
                            Nombre = "Seguros"
                        },
                        new
                        {
                            IdCategoria = 9,
                            Nombre = "Tecnología"
                        },
                        new
                        {
                            IdCategoria = 10,
                            Nombre = "Hotelería"
                        },
                        new
                        {
                            IdCategoria = 11,
                            Nombre = "Transporte"
                        },
                        new
                        {
                            IdCategoria = 12,
                            Nombre = "Alimentación"
                        },
                        new
                        {
                            IdCategoria = 13,
                            Nombre = "Farmacéutica"
                        },
                        new
                        {
                            IdCategoria = 14,
                            Nombre = "Inmobiliaria"
                        },
                        new
                        {
                            IdCategoria = 15,
                            Nombre = "Seguridad"
                        },
                        new
                        {
                            IdCategoria = 16,
                            Nombre = "Construcción"
                        },
                        new
                        {
                            IdCategoria = 17,
                            Nombre = "Logística"
                        });
                });

            modelBuilder.Entity("Buscador.Models.Ciudad", b =>
                {
                    b.Property<int>("IdCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCiudad"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCiudad");

                    b.ToTable("Ciudadades");

                    b.HasData(
                        new
                        {
                            IdCiudad = 1,
                            Nombre = "Madrid"
                        },
                        new
                        {
                            IdCiudad = 2,
                            Nombre = "Barcelona"
                        },
                        new
                        {
                            IdCiudad = 3,
                            Nombre = "Valencia"
                        },
                        new
                        {
                            IdCiudad = 4,
                            Nombre = "Sevilla"
                        },
                        new
                        {
                            IdCiudad = 5,
                            Nombre = "Zaragoza"
                        },
                        new
                        {
                            IdCiudad = 6,
                            Nombre = "Málaga"
                        },
                        new
                        {
                            IdCiudad = 7,
                            Nombre = "Murcia"
                        },
                        new
                        {
                            IdCiudad = 8,
                            Nombre = "Palma de Mallorca"
                        },
                        new
                        {
                            IdCiudad = 9,
                            Nombre = "Las Palmas de Gran Canaria"
                        },
                        new
                        {
                            IdCiudad = 10,
                            Nombre = "Bilbao"
                        },
                        new
                        {
                            IdCiudad = 11,
                            Nombre = "Alicante"
                        },
                        new
                        {
                            IdCiudad = 12,
                            Nombre = "Córdoba"
                        },
                        new
                        {
                            IdCiudad = 13,
                            Nombre = "Valladolid"
                        },
                        new
                        {
                            IdCiudad = 14,
                            Nombre = "Vigo"
                        },
                        new
                        {
                            IdCiudad = 15,
                            Nombre = "Gijón"
                        },
                        new
                        {
                            IdCiudad = 16,
                            Nombre = "Eibar"
                        },
                        new
                        {
                            IdCiudad = 17,
                            Nombre = "Tarragona"
                        },
                        new
                        {
                            IdCiudad = 18,
                            Nombre = "Lérida"
                        },
                        new
                        {
                            IdCiudad = 19,
                            Nombre = "Huelva"
                        },
                        new
                        {
                            IdCiudad = 20,
                            Nombre = "Granada"
                        },
                        new
                        {
                            IdCiudad = 21,
                            Nombre = "Jaén"
                        },
                        new
                        {
                            IdCiudad = 22,
                            Nombre = "Almería"
                        },
                        new
                        {
                            IdCiudad = 23,
                            Nombre = "Toledo"
                        },
                        new
                        {
                            IdCiudad = 24,
                            Nombre = "Salamanca"
                        },
                        new
                        {
                            IdCiudad = 25,
                            Nombre = "Segovia"
                        },
                        new
                        {
                            IdCiudad = 26,
                            Nombre = "Soria"
                        },
                        new
                        {
                            IdCiudad = 27,
                            Nombre = "Badajoz"
                        },
                        new
                        {
                            IdCiudad = 28,
                            Nombre = "Cáceres"
                        },
                        new
                        {
                            IdCiudad = 29,
                            Nombre = "Logroño"
                        },
                        new
                        {
                            IdCiudad = 30,
                            Nombre = "Pamplona"
                        });
                });

            modelBuilder.Entity("Buscador.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeticionIdPeticion")
                        .HasColumnType("int");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("PeticionIdPeticion");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            IdEmpresa = 1,
                            Descripcion = "Líder mundial en distribución de moda.",
                            Direccion = "Av. de la Diputación, 15142 Arteijo, La Coruña",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/inditexLC.jpg?updatedAt=1726649179851",
                            Nombre = "Inditex"
                        },
                        new
                        {
                            IdEmpresa = 2,
                            Descripcion = "Una de las mayores entidades bancarias del mundo.",
                            Direccion = "Ciudad Grupo Santander, 28660 Boadilla del Monte, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/santander.jpg?updatedAt=1726649877238",
                            Nombre = "Banco Santander"
                        },
                        new
                        {
                            IdEmpresa = 3,
                            Descripcion = "Multinacional española de telecomunicaciones.",
                            Direccion = "Distrito Telefónica, 28050 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/telefonica.jpg?updatedAt=1726649877081",
                            Nombre = "Telefónica"
                        },
                        new
                        {
                            IdEmpresa = 4,
                            Descripcion = "Una de las mayores empresas energéticas del mundo.",
                            Direccion = "Plaza Euskadi 5, 48009 Bilbao",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/iberdrola-.jpg?updatedAt=1726649877427",
                            Nombre = "Iberdrola"
                        },
                        new
                        {
                            IdEmpresa = 5,
                            Descripcion = "Empresa energética multinacional española.",
                            Direccion = "Calle Méndez Álvaro, 44, 28045 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/repsol.webp?updatedAt=1726649877458",
                            Nombre = "Repsol"
                        },
                        new
                        {
                            IdEmpresa = 6,
                            Descripcion = "Cadena de grandes almacenes más grande de Europa.",
                            Direccion = "Calle Hermosilla, 112, 28009 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/elcorteingles.jpeg?updatedAt=1726649879087",
                            Nombre = "El Corte Inglés"
                        },
                        new
                        {
                            IdEmpresa = 7,
                            Descripcion = "Uno de los bancos más importantes de España.",
                            Direccion = "Av. Diagonal, 621, 08028 Barcelona",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/caixabanck.jpg?updatedAt=1726649879170",
                            Nombre = "CaixaBank"
                        },
                        new
                        {
                            IdEmpresa = 8,
                            Descripcion = "Fabricante de automóviles con sede en Martorell.",
                            Direccion = "Autovía A-2, Km 585, 08760 Martorell, Barcelona",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/seat.jpg?updatedAt=1726649876969",
                            Nombre = "Seat"
                        },
                        new
                        {
                            IdEmpresa = 9,
                            Descripcion = "Gestión de aeropuertos en España y en el mundo.",
                            Direccion = "Calle Peonías, 12, 28042 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/aena-aeropuerto.jpg?updatedAt=1726649877286",
                            Nombre = "Aena"
                        },
                        new
                        {
                            IdEmpresa = 10,
                            Descripcion = "Empresa global de infraestructuras y servicios.",
                            Direccion = "Calle Príncipe de Vergara, 135, 28002 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/ferrovial.jpeg?updatedAt=1726649879406",
                            Nombre = "Ferrovial"
                        },
                        new
                        {
                            IdEmpresa = 11,
                            Descripcion = "Compañía de seguros global.",
                            Direccion = "Carretera de Pozuelo, 52, 28220 Majadahonda, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/mafre.jpg?updatedAt=1726649877454",
                            Nombre = "Mapfre"
                        },
                        new
                        {
                            IdEmpresa = 12,
                            Descripcion = "Líder en energías renovables y construcción sostenible.",
                            Direccion = "Avenida de Europa, 18, 28108 Alcobendas, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/acciona.webp?updatedAt=1726649877393",
                            Nombre = "Acciona"
                        },
                        new
                        {
                            IdEmpresa = 13,
                            Descripcion = "Multinacional de banca y servicios financieros.",
                            Direccion = "Calle Azul, 4, 28050 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/BBVA.jpg?updatedAt=1726649879175",
                            Nombre = "BBVA"
                        },
                        new
                        {
                            IdEmpresa = 14,
                            Descripcion = "Proveedor líder de tecnología en la industria del viaje.",
                            Direccion = "Calle Salvador de Madariaga, 1, 28027 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/amadeus.jpg?updatedAt=1726649879691",
                            Nombre = "Amadeus"
                        },
                        new
                        {
                            IdEmpresa = 15,
                            Descripcion = "Líder global en el sector de los hemoderivados.",
                            Direccion = "Calle Jesús i Maria, 6, 08022 Barcelona",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/grifols.jpg?updatedAt=1726649877212",
                            Nombre = "Grifols"
                        },
                        new
                        {
                            IdEmpresa = 16,
                            Descripcion = "Una de las mayores marcas de moda del mundo.",
                            Direccion = "Av. de la Diputación, 15142 Arteijo, La Coruña",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/zara.jpg?updatedAt=1726649877219",
                            Nombre = "Zara"
                        },
                        new
                        {
                            IdEmpresa = 17,
                            Descripcion = "Cadena de supermercados líder en España.",
                            Direccion = "Calle Valencia, 5, 46016 Tavernes Blanques, Valencia",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/mercadona.jpg?updatedAt=1726649879213",
                            Nombre = "Mercadona"
                        },
                        new
                        {
                            IdEmpresa = 18,
                            Descripcion = "Cadena de hoteles con presencia internacional.",
                            Direccion = "Calle Gremio Toneleros, 24, 07009 Palma, Islas Baleares",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/meliahotels.jpg?updatedAt=1726649879218",
                            Nombre = "Meliá Hotels"
                        },
                        new
                        {
                            IdEmpresa = 19,
                            Descripcion = "Empresa multinacional de gas y electricidad.",
                            Direccion = "Avenida de América, 38, 28028 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/naturgy.jpg?updatedAt=1726649879220",
                            Nombre = "Naturgy"
                        },
                        new
                        {
                            IdEmpresa = 20,
                            Descripcion = "Empresa de construcción y servicios.",
                            Direccion = "Calle Federico Salmón, 13, 28016 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/fcc.jpg?updatedAt=1726649879225",
                            Nombre = "FCC"
                        },
                        new
                        {
                            IdEmpresa = 21,
                            Descripcion = "Multinacional en construcción e infraestructuras.",
                            Direccion = "Calle Condesa de Venadito, 7, 28027 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/sacyr.jpg?updatedAt=1726649879229",
                            Nombre = "Sacyr"
                        },
                        new
                        {
                            IdEmpresa = 22,
                            Descripcion = "Operador europeo de infraestructuras de telecomunicaciones.",
                            Direccion = "Calle Juan Esplandiú, 11, 28007 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/cellnex.jpg?updatedAt=1726649879231",
                            Nombre = "Cellnex"
                        },
                        new
                        {
                            IdEmpresa = 23,
                            Descripcion = "Grupo turístico líder en España.",
                            Direccion = "Calle de la Cruz, 1, 28760 Tres Cantos, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/globalia.jpg?updatedAt=1726649879233",
                            Nombre = "Globalia"
                        },
                        new
                        {
                            IdEmpresa = 24,
                            Descripcion = "Líder mundial en envolturas alimentarias.",
                            Direccion = "Polígono Industrial Berroa, 15, 31192 Tajonar, Navarra",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/viscofan.jpg?updatedAt=1726649879236",
                            Nombre = "Viscofan"
                        },
                        new
                        {
                            IdEmpresa = 25,
                            Descripcion = "Multinacional de energía.",
                            Direccion = "Torre Cepsa, Paseo de la Castellana, 259A, 28046 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/cepsa.jpg?updatedAt=1726649879240",
                            Nombre = "Cepsa"
                        },
                        new
                        {
                            IdEmpresa = 26,
                            Descripcion = "Empresa líder en seguridad privada.",
                            Direccion = "Calle Pajaritos, 24, 28007 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/prosegur.jpg?updatedAt=1726649879245",
                            Nombre = "Prosegur"
                        },
                        new
                        {
                            IdEmpresa = 27,
                            Descripcion = "Multinacional de consultoría y tecnología.",
                            Direccion = "Avenida de Bruselas, 35, 28108 Alcobendas, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/indra.jpg?updatedAt=1726649879249",
                            Nombre = "Indra"
                        },
                        new
                        {
                            IdEmpresa = 28,
                            Descripcion = "Empresa líder en el sector inmobiliario.",
                            Direccion = "Paseo de la Castellana, 163, 28046 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/colonial.jpg?updatedAt=1726649879252",
                            Nombre = "Colonial"
                        },
                        new
                        {
                            IdEmpresa = 29,
                            Descripcion = "Cadena hotelera con presencia internacional.",
                            Direccion = "Calle Santa Engracia, 120, 28003 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/nhhotelgroup.jpg?updatedAt=1726649879256",
                            Nombre = "NH Hotel Group"
                        },
                        new
                        {
                            IdEmpresa = 30,
                            Descripcion = "Líder en el sector alimentario.",
                            Direccion = "Calle del Prado, 6, 28014 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/ebrofoods.jpg?updatedAt=1726649879261",
                            Nombre = "Ebro Foods"
                        },
                        new
                        {
                            IdEmpresa = 31,
                            Descripcion = "Compañía farmacéutica internacional.",
                            Direccion = "Ronda General Mitre, 151, 08022 Barcelona",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/almirall.jpg?updatedAt=1726649879266",
                            Nombre = "Almirall"
                        },
                        new
                        {
                            IdEmpresa = 32,
                            Descripcion = "Empresa farmacéutica especializada en productos inyectables.",
                            Direccion = "Calle Julián Camarillo, 35, 28037 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/rovi.jpg?updatedAt=1726649879270",
                            Nombre = "Rovi"
                        },
                        new
                        {
                            IdEmpresa = 33,
                            Descripcion = "Operador líder en transporte de pasajeros.",
                            Direccion = "Calle Miguel Fleta, 4, 28037 Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/alsa.jpg?updatedAt=1726649879275",
                            Nombre = "Alsa"
                        },
                        new
                        {
                            IdEmpresa = 34,
                            Descripcion = "Multinacional de productos de colágeno y envolturas.",
                            Direccion = "Polígono Berroa, 15, 31192 Tajonar, Navarra",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/viscofan.jpg?updatedAt=1726649879279",
                            Nombre = "Viscofan"
                        },
                        new
                        {
                            IdEmpresa = 35,
                            Descripcion = "Empresa farmacéutica especializada en productos oncológicos.",
                            Direccion = "Avenida de los Reyes, 1, 28760 Tres Cantos, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/pharmamar.jpg?updatedAt=1726649879283",
                            Nombre = "Pharmamar"
                        },
                        new
                        {
                            IdEmpresa = 36,
                            Descripcion = "Distribuidora líder en el sur de Europa.",
                            Direccion = "Avenida de la Vega, 1, 28108 Alcobendas, Madrid",
                            Imagen = "https://ik.imagekit.io/Mariocanizares/Empresas/logista.jpg?updatedAt=1726649879286",
                            Nombre = "Logista"
                        });
                });

            modelBuilder.Entity("Buscador.Models.EmpresaCategoria", b =>
                {
                    b.Property<int>("IdEmpresaCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresaCategoria"), 1L, 1);

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdEmpresaCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("EmpresaCategorias");

                    b.HasData(
                        new
                        {
                            IdEmpresaCategoria = 1,
                            IdCategoria = 1,
                            IdEmpresa = 1
                        },
                        new
                        {
                            IdEmpresaCategoria = 2,
                            IdCategoria = 2,
                            IdEmpresa = 2
                        },
                        new
                        {
                            IdEmpresaCategoria = 3,
                            IdCategoria = 3,
                            IdEmpresa = 3
                        },
                        new
                        {
                            IdEmpresaCategoria = 4,
                            IdCategoria = 4,
                            IdEmpresa = 4
                        },
                        new
                        {
                            IdEmpresaCategoria = 5,
                            IdCategoria = 4,
                            IdEmpresa = 5
                        },
                        new
                        {
                            IdEmpresaCategoria = 6,
                            IdCategoria = 5,
                            IdEmpresa = 6
                        },
                        new
                        {
                            IdEmpresaCategoria = 7,
                            IdCategoria = 2,
                            IdEmpresa = 7
                        },
                        new
                        {
                            IdEmpresaCategoria = 8,
                            IdCategoria = 6,
                            IdEmpresa = 8
                        },
                        new
                        {
                            IdEmpresaCategoria = 9,
                            IdCategoria = 11,
                            IdEmpresa = 9
                        },
                        new
                        {
                            IdEmpresaCategoria = 10,
                            IdCategoria = 7,
                            IdEmpresa = 10
                        },
                        new
                        {
                            IdEmpresaCategoria = 11,
                            IdCategoria = 8,
                            IdEmpresa = 11
                        },
                        new
                        {
                            IdEmpresaCategoria = 12,
                            IdCategoria = 7,
                            IdEmpresa = 12
                        },
                        new
                        {
                            IdEmpresaCategoria = 13,
                            IdCategoria = 2,
                            IdEmpresa = 13
                        },
                        new
                        {
                            IdEmpresaCategoria = 14,
                            IdCategoria = 9,
                            IdEmpresa = 14
                        },
                        new
                        {
                            IdEmpresaCategoria = 15,
                            IdCategoria = 13,
                            IdEmpresa = 15
                        },
                        new
                        {
                            IdEmpresaCategoria = 16,
                            IdCategoria = 1,
                            IdEmpresa = 16
                        },
                        new
                        {
                            IdEmpresaCategoria = 17,
                            IdCategoria = 12,
                            IdEmpresa = 17
                        },
                        new
                        {
                            IdEmpresaCategoria = 18,
                            IdCategoria = 10,
                            IdEmpresa = 18
                        },
                        new
                        {
                            IdEmpresaCategoria = 19,
                            IdCategoria = 4,
                            IdEmpresa = 19
                        },
                        new
                        {
                            IdEmpresaCategoria = 20,
                            IdCategoria = 16,
                            IdEmpresa = 20
                        },
                        new
                        {
                            IdEmpresaCategoria = 21,
                            IdCategoria = 16,
                            IdEmpresa = 21
                        },
                        new
                        {
                            IdEmpresaCategoria = 22,
                            IdCategoria = 3,
                            IdEmpresa = 22
                        },
                        new
                        {
                            IdEmpresaCategoria = 23,
                            IdCategoria = 9,
                            IdEmpresa = 23
                        },
                        new
                        {
                            IdEmpresaCategoria = 24,
                            IdCategoria = 12,
                            IdEmpresa = 24
                        },
                        new
                        {
                            IdEmpresaCategoria = 25,
                            IdCategoria = 4,
                            IdEmpresa = 25
                        },
                        new
                        {
                            IdEmpresaCategoria = 26,
                            IdCategoria = 15,
                            IdEmpresa = 26
                        },
                        new
                        {
                            IdEmpresaCategoria = 27,
                            IdCategoria = 9,
                            IdEmpresa = 27
                        },
                        new
                        {
                            IdEmpresaCategoria = 28,
                            IdCategoria = 14,
                            IdEmpresa = 28
                        },
                        new
                        {
                            IdEmpresaCategoria = 29,
                            IdCategoria = 10,
                            IdEmpresa = 29
                        },
                        new
                        {
                            IdEmpresaCategoria = 30,
                            IdCategoria = 12,
                            IdEmpresa = 30
                        },
                        new
                        {
                            IdEmpresaCategoria = 31,
                            IdCategoria = 13,
                            IdEmpresa = 31
                        },
                        new
                        {
                            IdEmpresaCategoria = 32,
                            IdCategoria = 13,
                            IdEmpresa = 32
                        },
                        new
                        {
                            IdEmpresaCategoria = 33,
                            IdCategoria = 11,
                            IdEmpresa = 33
                        },
                        new
                        {
                            IdEmpresaCategoria = 34,
                            IdCategoria = 12,
                            IdEmpresa = 34
                        },
                        new
                        {
                            IdEmpresaCategoria = 35,
                            IdCategoria = 13,
                            IdEmpresa = 35
                        },
                        new
                        {
                            IdEmpresaCategoria = 36,
                            IdCategoria = 17,
                            IdEmpresa = 36
                        });
                });

            modelBuilder.Entity("Buscador.Models.EmpresaCiudad", b =>
                {
                    b.Property<int>("IdEmpresaCiudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresaCiudad"), 1L, 1);

                    b.Property<int>("IdCiudad")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.HasKey("IdEmpresaCiudad");

                    b.HasIndex("IdCiudad");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("EmpresasCiudades");

                    b.HasData(
                        new
                        {
                            IdEmpresaCiudad = 1,
                            IdCiudad = 1,
                            IdEmpresa = 1
                        },
                        new
                        {
                            IdEmpresaCiudad = 2,
                            IdCiudad = 2,
                            IdEmpresa = 1
                        },
                        new
                        {
                            IdEmpresaCiudad = 3,
                            IdCiudad = 3,
                            IdEmpresa = 2
                        },
                        new
                        {
                            IdEmpresaCiudad = 4,
                            IdCiudad = 3,
                            IdEmpresa = 3
                        },
                        new
                        {
                            IdEmpresaCiudad = 5,
                            IdCiudad = 4,
                            IdEmpresa = 4
                        },
                        new
                        {
                            IdEmpresaCiudad = 6,
                            IdCiudad = 3,
                            IdEmpresa = 5
                        },
                        new
                        {
                            IdEmpresaCiudad = 7,
                            IdCiudad = 3,
                            IdEmpresa = 6
                        },
                        new
                        {
                            IdEmpresaCiudad = 8,
                            IdCiudad = 2,
                            IdEmpresa = 6
                        },
                        new
                        {
                            IdEmpresaCiudad = 9,
                            IdCiudad = 2,
                            IdEmpresa = 7
                        },
                        new
                        {
                            IdEmpresaCiudad = 10,
                            IdCiudad = 2,
                            IdEmpresa = 8
                        },
                        new
                        {
                            IdEmpresaCiudad = 11,
                            IdCiudad = 3,
                            IdEmpresa = 9
                        },
                        new
                        {
                            IdEmpresaCiudad = 12,
                            IdCiudad = 3,
                            IdEmpresa = 10
                        },
                        new
                        {
                            IdEmpresaCiudad = 13,
                            IdCiudad = 3,
                            IdEmpresa = 11
                        },
                        new
                        {
                            IdEmpresaCiudad = 14,
                            IdCiudad = 3,
                            IdEmpresa = 12
                        },
                        new
                        {
                            IdEmpresaCiudad = 15,
                            IdCiudad = 3,
                            IdEmpresa = 13
                        },
                        new
                        {
                            IdEmpresaCiudad = 16,
                            IdCiudad = 3,
                            IdEmpresa = 14
                        },
                        new
                        {
                            IdEmpresaCiudad = 17,
                            IdCiudad = 2,
                            IdEmpresa = 15
                        },
                        new
                        {
                            IdEmpresaCiudad = 18,
                            IdCiudad = 1,
                            IdEmpresa = 16
                        },
                        new
                        {
                            IdEmpresaCiudad = 19,
                            IdCiudad = 2,
                            IdEmpresa = 16
                        },
                        new
                        {
                            IdEmpresaCiudad = 20,
                            IdCiudad = 2,
                            IdEmpresa = 17
                        },
                        new
                        {
                            IdEmpresaCiudad = 21,
                            IdCiudad = 2,
                            IdEmpresa = 18
                        },
                        new
                        {
                            IdEmpresaCiudad = 22,
                            IdCiudad = 3,
                            IdEmpresa = 19
                        },
                        new
                        {
                            IdEmpresaCiudad = 23,
                            IdCiudad = 3,
                            IdEmpresa = 20
                        },
                        new
                        {
                            IdEmpresaCiudad = 24,
                            IdCiudad = 3,
                            IdEmpresa = 21
                        },
                        new
                        {
                            IdEmpresaCiudad = 25,
                            IdCiudad = 3,
                            IdEmpresa = 22
                        },
                        new
                        {
                            IdEmpresaCiudad = 26,
                            IdCiudad = 2,
                            IdEmpresa = 23
                        },
                        new
                        {
                            IdEmpresaCiudad = 27,
                            IdCiudad = 1,
                            IdEmpresa = 24
                        },
                        new
                        {
                            IdEmpresaCiudad = 28,
                            IdCiudad = 3,
                            IdEmpresa = 25
                        },
                        new
                        {
                            IdEmpresaCiudad = 29,
                            IdCiudad = 3,
                            IdEmpresa = 26
                        },
                        new
                        {
                            IdEmpresaCiudad = 30,
                            IdCiudad = 3,
                            IdEmpresa = 27
                        },
                        new
                        {
                            IdEmpresaCiudad = 31,
                            IdCiudad = 3,
                            IdEmpresa = 28
                        },
                        new
                        {
                            IdEmpresaCiudad = 32,
                            IdCiudad = 3,
                            IdEmpresa = 29
                        },
                        new
                        {
                            IdEmpresaCiudad = 33,
                            IdCiudad = 3,
                            IdEmpresa = 30
                        },
                        new
                        {
                            IdEmpresaCiudad = 34,
                            IdCiudad = 2,
                            IdEmpresa = 31
                        },
                        new
                        {
                            IdEmpresaCiudad = 35,
                            IdCiudad = 3,
                            IdEmpresa = 32
                        },
                        new
                        {
                            IdEmpresaCiudad = 36,
                            IdCiudad = 3,
                            IdEmpresa = 33
                        },
                        new
                        {
                            IdEmpresaCiudad = 37,
                            IdCiudad = 3,
                            IdEmpresa = 34
                        },
                        new
                        {
                            IdEmpresaCiudad = 38,
                            IdCiudad = 3,
                            IdEmpresa = 35
                        },
                        new
                        {
                            IdEmpresaCiudad = 39,
                            IdCiudad = 3,
                            IdEmpresa = 36
                        },
                        new
                        {
                            IdEmpresaCiudad = 40,
                            IdCiudad = 1,
                            IdEmpresa = 15
                        },
                        new
                        {
                            IdEmpresaCiudad = 41,
                            IdCiudad = 1,
                            IdEmpresa = 18
                        },
                        new
                        {
                            IdEmpresaCiudad = 42,
                            IdCiudad = 1,
                            IdEmpresa = 26
                        },
                        new
                        {
                            IdEmpresaCiudad = 43,
                            IdCiudad = 1,
                            IdEmpresa = 29
                        },
                        new
                        {
                            IdEmpresaCiudad = 44,
                            IdCiudad = 2,
                            IdEmpresa = 10
                        },
                        new
                        {
                            IdEmpresaCiudad = 45,
                            IdCiudad = 4,
                            IdEmpresa = 12
                        },
                        new
                        {
                            IdEmpresaCiudad = 46,
                            IdCiudad = 4,
                            IdEmpresa = 19
                        },
                        new
                        {
                            IdEmpresaCiudad = 47,
                            IdCiudad = 2,
                            IdEmpresa = 9
                        },
                        new
                        {
                            IdEmpresaCiudad = 48,
                            IdCiudad = 3,
                            IdEmpresa = 1
                        });
                });

            modelBuilder.Entity("Buscador.Models.Peticion", b =>
                {
                    b.Property<int>("IdPeticion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPeticion"), 1L, 1);

                    b.Property<string>("DescripcionEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCategoriaEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdCiudadEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ImagenEmpresaURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPeticion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Peticiones");
                });

            modelBuilder.Entity("Buscador.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Buscador.Models.UsuarioEmpresa", b =>
                {
                    b.Property<int>("IdUsuarioEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuarioEmpresa"), 1L, 1);

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdUsuarioEmpresa");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdUsuario");

                    b.ToTable("UsuarioEmpresas");
                });

            modelBuilder.Entity("Buscador.Models.Empresa", b =>
                {
                    b.HasOne("Buscador.Models.Peticion", "Peticion")
                        .WithMany()
                        .HasForeignKey("PeticionIdPeticion");

                    b.Navigation("Peticion");
                });

            modelBuilder.Entity("Buscador.Models.EmpresaCategoria", b =>
                {
                    b.HasOne("Buscador.Models.Categoria", "Categoria")
                        .WithMany("EmpresaCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buscador.Models.Empresa", "Empresa")
                        .WithMany("EmpresaCategorias")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Buscador.Models.EmpresaCiudad", b =>
                {
                    b.HasOne("Buscador.Models.Ciudad", "Ciudad")
                        .WithMany("EmpresasCiudades")
                        .HasForeignKey("IdCiudad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buscador.Models.Empresa", "Empresa")
                        .WithMany("EmpresasCiudades")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciudad");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Buscador.Models.Peticion", b =>
                {
                    b.HasOne("Buscador.Models.Usuario", "Usuario")
                        .WithMany("Peticiones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buscador.Models.UsuarioEmpresa", b =>
                {
                    b.HasOne("Buscador.Models.Empresa", "Empresa")
                        .WithMany("UsuarioEmpresas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buscador.Models.Usuario", "Usuario")
                        .WithMany("MisEmpresas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Buscador.Models.Categoria", b =>
                {
                    b.Navigation("EmpresaCategorias");
                });

            modelBuilder.Entity("Buscador.Models.Ciudad", b =>
                {
                    b.Navigation("EmpresasCiudades");
                });

            modelBuilder.Entity("Buscador.Models.Empresa", b =>
                {
                    b.Navigation("EmpresaCategorias");

                    b.Navigation("EmpresasCiudades");

                    b.Navigation("UsuarioEmpresas");
                });

            modelBuilder.Entity("Buscador.Models.Usuario", b =>
                {
                    b.Navigation("MisEmpresas");

                    b.Navigation("Peticiones");
                });
#pragma warning restore 612, 618
        }
    }
}
